[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan cache:clear',
    'php artisan view:clear'
]

[start]
cmd = 'php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
